---
- name: Install Clickhouse & Vector
  hosts: clickhouse
  gather_facts: false

  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

    - name: Start Vector service
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: false
        name: vector.service
        state: started

  tasks:
    - block:
        - block:
            - name: Clickhouse | Get distrib
              ansible.builtin.get_url:
                url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse/{{ item }}_{{ clickhouse_version }}_amd64.deb"
                dest: "{{ workdir }}/{{ item }}_{{ clickhouse_version }}_amd64.deb"
                mode: 0644
              with_items: "{{ clickhouse_packages }}"
          rescue:
            - name: Clickhouse | Get distrib
              ansible.builtin.get_url:
                url: "https://packages.clickhouse.com/deb/pool/main/c/clickhouse/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
                dest: "{{ workdir }}/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
                mode: 0644
              with_items: "{{ clickhouse_packages }}"

        - name: Clickhouse | Install package clickhouse-common-static
          become: true
          ansible.builtin.apt:
            deb: "{{ workdir }}/clickhouse-common-static_{{ clickhouse_version }}_amd64.deb"
          notify: Start clickhouse service

        - name: Clickhouse | Install package clickhouse-client
          become: true
          ansible.builtin.apt:
            deb: "{{ workdir }}/clickhouse-client_{{ clickhouse_version }}_amd64.deb"
          notify: Start clickhouse service

        - name: Clickhouse | Install package clickhouse-server
          become: true
          ansible.builtin.apt:
            deb: "{{ workdir }}/clickhouse-server_{{ clickhouse_version }}_amd64.deb"
          notify: Start clickhouse service

        - name: Clickhouse | Flush handlers
          ansible.builtin.meta: flush_handlers

        - name: Clickhouse | Waiting for start
          ansible.builtin.pause:
            seconds: 10
            echo: false

        - name: Clickhouse | Create database
          ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
          register: create_db
          failed_when: create_db.rc != 0 and create_db.rc !=82
          changed_when: create_db.rc == 0
      tags: clickhouse

    - block:
        - name: Vector | Create work directory
          ansible.builtin.file:
            path: "{{ workdir }}/vector"
            state: directory
            mode: 0755

        - name: Vector | Get distributive
          ansible.builtin.get_url:
            url: "https://packages.timber.io/vector/0.38.0/vector-0.38.0-x86_64-unknown-linux-gnu.tar.gz"
            dest: "{{ workdir }}/vector/vector-0.38.0-x86_64-unknown-linux-gnu.tar.gz"
            mode: 0644

        - name: Vector | Unzip
          ansible.builtin.unarchive:
            remote_src: true
            src: "{{ workdir }}/vector/vector-0.38.0-x86_64-unknown-linux-gnu.tar.gz"
            dest: "{{ workdir }}/vector"

        - name: Vector | Install binary 
          become: true
          ansible.builtin.copy:
            remote_src: true
            src: "{{ workdir }}/vector/vector-x86_64-unknown-linux-gnu/bin/vector"
            dest: "/usr/bin/"
            mode: 0755
            owner: root
            group: root

        - name: Vector | Check installation
          ansible.builtin.command: "vector --version"
          register: var_vector
          failed_when: var_vector.rc != 0
          changed_when: var_vector.rc == 0

        - name: Vector | Create Vector config
          become: true
          ansible.builtin.copy:
            remote_src: true
            src: "{{ workdir }}/vector/vector-x86_64-unknown-linux-gnu/config/vector.yaml"
            dest: "/etc/vector/"
            mode: 0644
            owner: root
            group: root

        - name: Vector | Create vector.service daemon
          become: true
          ansible.builtin.copy:
            remote_src: true
            src: "{{ workdir }}/vector/vector-x86_64-unknown-linux-gnu/etc/systemd/vector.service"
            dest: "/lib/systemd/system/"
            mode: 0644
            owner: root
            group: root
          notify: Start Vector service

        - name: Vector | Modify vector.service file
          become: true
          ansible.builtin.replace:
            backup: true
            path: "/lib/systemd/system/vector.service"
            regexp: "^ExecStart=/usr/bin/vector$"
            replace: "ExecStart=/usr/bin/vector --config /etc/vector/vector.yaml"
          notify: Start Vector service

        - name: Vector | Create user vector
          become: true
          ansible.builtin.user:
            create_home: false
            name: "vector"

        - name: Vector | Create data_dir
          become: true
          ansible.builtin.file:
            path: "/var/lib/vector"
            state: directory
            mode: 0755
            owner: "vector"
            group: "vector"

        - name: Vector | Remove work directory
          ansible.builtin.file:
            path: "{{ workdir }}/vector"
            state: absent

      tags: vector

- name: Install Lighthouse
  hosts: lighthouse
  gather_facts: false

  handlers:
    - name: Start Lighthouse service
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
        enabled: false
        name: nginx.service
        state: started
  
  tasks:
    - block:
        - name: Lighthouse. Pre-install git client
          become: true
          ansible.builtin.apt:
            name: "git"
            update_cache: true
        
        - name: Lighthouse. Pre-install nginx
          become: true
          ansible.builtin.apt:
            name: "nginx"
            update_cache: true

        - name: Lighthouse. Clone source code by git client
          become: true
          ansible.builtin.git:
            repo: "https://github.com/VKCOM/lighthouse.git"
            dest: "/home/ubuntu/lighthouse/"

        - name: Lighthouse. Prepare nginx config
          become: true
          ansible.builtin.template:
            src: "templates/lighthouse.conf.j2"
            dest: "/etc/nginx/conf.d/lighthouse.conf"
          notify: Start Lighthouse service

      tags: lighthouse